name: Build Nextjs app and deploy to Netlify.

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ['main']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    environment:
      name: Nextjs Build Env
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: 'next-server/pnpm-lock.yaml'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/next-server/.next/cache
          key: |
            ${{ runner.os }}-nextjs-${{ hashFiles('next-server/package-lock.json') }}-${{ hashFiles('next-server/**.[jt]s', 'next-server/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('next-server/package-lock.json') }}-

      - name: Install dependencies
        run: |
          cd next-server
          pnpm install --shamefully-hoist --frozen-lockfile

      - name: Build and deploy to Netlify
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd next-server

          pnpm netlify deploy --build --context production --prod --message "${{ github.event.head_commit.message }}@${{ github.sha }}"
